### ISSUE TITLE
"Замовити послуги" button has wrong position on iPad resolution

### ISSUE THREAD

**Issue by id-dan** [ArtemKaufman/Study#1]
**Actual Result:**
<img width="1377" alt="Screenshot 2022-06-21 at 13 09 50" src="https://user-images.githubusercontent.com/52101871/174775230-22d625bb-578e-4bbd-8788-7a8592dddc62.png">

**Expected Result:**
"Замовити послуги" button should be shown in background block

**Comment by ArtemKaufman** [comment]
I corrected
